title: FirstBlock Ventures
email: kyle@firstblock.com
description: >- # this means to ignore newlines until "baseurl:"
  FirstBlock Ventures LLC provides delegated validator services for the Cosmos.network ecosystem.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username:
medium_username: 
steemit_username: "@firstblock" 
facebook_url: 
twitter_username: FirstBlockV
github_username:  

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Google Analytics
google_analytics: UA—121792142-1
